name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Server
      run: wget https://raw.githubusercontent.com/raiyan088/public/main/github/server.js
    - run: node server.js
